Added CHANGELOG and PR tempate
BU-ISCIII/buisciii-tools pull request #182
Opened 2024-01-15 14:31 UTC by svarona

2024-01-15 14:52 UTC, saramonzon requested changes

2024-01-15 14:52 UTC, saramonzon commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
> +- [ ] Make sure your code lints (`nf-core lint`).
```suggestion
- [ ] Make sure your code lints (`black and flake8`).
```

2024-01-15 14:52 UTC, saramonzon commented on CHANGELOG.md
> +## [1.0.0] - 2024-01-08 : https://github.com/BU-ISCIII/buisciii-tools/releases/tag/1.0.0
Add also a 1.0.1 for the hotfixes branch

2024-01-15 16:16 UTC, saramonzon approved these changes

2024-01-16 08:30 UTC, closed without merging

2024-01-16 08:30 UTC, svarona commented
Made it to hotfix:
https://github.com/BU-ISCIII/buisciii-tools/pull/183